//Code is generated by ucloud code generator, don't modify it by hand, it will cause undefined behaviors.
//go:generate ucloud-gen-go-api UMon GetMetric

package ukafka

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// GetMetricRequest is request schema for GetMetric action
type GetShockwaveMetricRequest struct {
	request.CommonBase

	// 可用区。参见 [可用区列表](../summary/regionlist.html)
	// Zone *string `required:"false"`

	// 资源类型
	ResourceType *string `required:"true"`

	// 指标名称（不同ResourceType对应不同的MetricName）
	MetricName []string `required:"true"`

	// 资源Id（目前除sharebandwidth可以不传入ResourceId外，其他资源必须传入，sharebandwidth不传入会默认使用获取到的第一个资源Id）
	ResourceId []string `required:"true"`

	// 拉取最近多少秒的监控数据，默认1小时，即3600；最大1个月
	TimeRange *int `required:"false"`

	DistrictType *string `required:"true"`

	PublicIP []string `required:"true"`
}

// GetMetricResponse is response schema for GetMetric action
type GetShockwaveMetricResponse struct {
	response.CommonBase

	DataSet []MetricItemSet
}

// NewGetMetricRequest will create request of GetMetric action.
func (c *UKafkaClient) NewGetShockwaveMetric() *GetShockwaveMetricRequest {
	req := &GetShockwaveMetricRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// GetMetric - 获取监控数据
func (c *UKafkaClient) GetShockwaveMetric(req *GetShockwaveMetricRequest) (*GetShockwaveMetricResponse, error) {
	var err error
	var res GetShockwaveMetricResponse

	err = c.Client.InvokeAction("GetShockwaveMetric", req, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
